'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Landmark, Palette, Search, Megaphone, Settings2, Plus, Trash2, ArrowUp, ArrowDown, Check, Save, Upload} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {DemoState} from '@/lib/demo-data';
import {imageData,localMode} from '@/lib/demo-store';
import {toast} from 'sonner';
type Config=DemoState['settings'];
export function DiwanSettings({settings,sections,onSave}:{settings:Config;sections:DemoState['sections'];onSave:(s:Partial<Config>)=>Promise<boolean>}){
  const [draft,setDraft]=useState(()=>structuredClone(settings)),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false);
  useEffect(()=>{if(!dirty)setDraft(structuredClone(settings));},[settings,dirty]);
  const changed=useRef(new Set<keyof Config>());
  const change=(key:keyof Config,value:any)=>{changed.current.add(key);setDraft(d=>({...d,[key]:value}));setDirty(true);};
  const input=(key:keyof Config,label:string,type='text',hint?:string)=><label className="field">{label}<input aria-label={label} type={type} value={String(draft[key]??'')} onChange={e=>change(key,type==='number'?Number(e.target.value):e.target.value)} required={['siteName','homeTitle','seoTitle'].includes(key)}/>{hint&&<small>{hint}</small>}</label>;
  const area=(key:keyof Config,label:string)=><label className="field">{label}<textarea aria-label={label} rows={3} value={String(draft[key]||'')} onChange={e=>change(key,e.target.value)}/></label>;
  const toggle=(key:keyof Config,label:string,hint?:string)=><div className="switch-row"><div><b>{label}</b>{hint&&<small>{hint}</small>}</div><Switch aria-label={label} dir="ltr" checked={!!draft[key]} onCheckedChange={v=>change(key,v)}/></div>;
  const image=(key:'logo'|'favicon'|'seoImage',label:string)=><div className="field image-config"><span>{label}</span><div>{draft[key]?<img src={draft[key]} alt={label}/>:<span className="image-placeholder"><Landmark size={30}/></span>}<label className="btn outline compact"><Upload size={16}/>رفع صورة<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" aria-label={'رفع '+label} onChange={async e=>{const f=e.target.files?.[0];if(f)try{change(key,await imageData(f,key==='favicon'?128:key==='logo'?512:1200));}catch(err:any){toast.error(err.message);}}}/></label>{draft[key]&&<button className="btn ghost compact" type="button" onClick={()=>change(key,'')}>إزالة</button>}</div><small>PNG، JPG، WEBP · حتى 1 ميغابايت</small></div>;
  const news=(index:number,patch:any)=>change('tickerItems',draft.tickerItems.map((n,i)=>i===index?{...n,...patch}:n));
  const move=(index:number,offset:number)=>{const items=[...draft.tickerItems],dest=index+offset;if(dest<0||dest>=items.length)return;[items[index],items[dest]]=[items[dest],items[index]];change('tickerItems',items);};
  const save=async(e:React.FormEvent)=>{e.preventDefault();
    if(!draft.siteName.trim()||!draft.homeTitle.trim()||!draft.seoTitle.trim())return toast.error('أكمل اسم الموقع وعنوان الرئيسية وعنوان SEO');
    if(draft.seoTitle.length>100||draft.seoDescription.length>320)return toast.error('عنوان SEO حتى 100 حرف والوصف حتى 320 حرف');
    if(![draft.primaryColor,draft.accentColor,draft.backgroundColor,draft.textColor].every(c=>/^#[0-9a-f]{6}$/i.test(c)))return toast.error('أدخل ألوانًا صحيحة');
    const numbers:[number,number,number,string][]=[[draft.tickerSpeed,15,180,'سرعة الشريط'],[draft.postsPerPage,1,50,'عدد المواضيع'],[draft.postMaxLength,100,50000,'طول الموضوع'],[draft.commentMaxLength,10,5000,'طول التعليق'],[draft.chatMaxLength,10,5000,'طول الرسالة']];
    for(const [v,min,max,label] of numbers)if(!Number.isInteger(v)||v<min||v>max)return toast.error(`${label}: قيمة بين ${min} و${max}`);
    const urls=[draft.canonicalUrl,draft.instagramUrl,draft.youtubeUrl,draft.xUrl,...draft.tickerItems.map(n=>n.url)];
    if(urls.some(u=>u&&!/^https:\/\//i.test(u)))return toast.error('استخدم HTTPS للروابط');
    if(draft.tickerItems.some(n=>n.enabled&&!n.text.trim()))return toast.error('أكمل نص كل خبر مفعّل');
    setSaving(true);if(await onSave(Object.fromEntries([...changed.current].map(key=>[key,draft[key]])) as Partial<Config>)){changed.current.clear();setDirty(false);toast.success('حُفظت إعدادات الديوان');}setSaving(false);
  };
  return <form onSubmit={save} className="settings-form"><Tabs defaultValue="identity" dir="rtl"><TabsList className="app-tabs settings-tabs">
    <TabsTrigger value="identity"><Landmark size={16}/>هوية الموقع</TabsTrigger><TabsTrigger value="home">الصفحة الرئيسية</TabsTrigger><TabsTrigger value="appearance"><Palette size={16}/>المظهر</TabsTrigger><TabsTrigger value="seo"><Search size={16}/>SEO</TabsTrigger><TabsTrigger value="news"><Megaphone size={16}/>الشريط الإخباري</TabsTrigger><TabsTrigger value="features"><Settings2 size={16}/>خصائص الديوان</TabsTrigger>
  </TabsList>
  <TabsContent value="identity"><section className="panel"><h2>الاسم وبيانات الديوان</h2><p>تظهر الهوية في القائمة، رأس الصفحة وشاشة التسجيل.</p><div className="settings-grid">{input('siteName','اسم الموقع')}{input('siteSubtitle','الاسم الفرعي / عنوان الموقع')}{image('logo','شعار الموقع')}{image('favicon','أيقونة المتصفح')}{input('contactEmail','البريد الإلكتروني','email')}{input('contactPhone','رقم التواصل','tel')}{input('contactAddress','العنوان')}{input('instagramUrl','رابط Instagram','url')}{input('youtubeUrl','رابط YouTube','url')}{input('xUrl','رابط X','url')}</div>{area('footerText','النص في تذييل الموقع')}</section></TabsContent>
  <TabsContent value="home"><section className="panel"><h2>محتوى الصفحة الرئيسية</h2><p>تحكم بالعنوان الظاهر، الترحيب ونصوص واجهة الديوان.</p><div className="settings-grid">{input('homeTitle','عنوان الصفحة الرئيسية')}{input('heroLabel','عبارة أعلى بطاقة الترحيب')}{input('heroHeading','عنوان بطاقة الترحيب')}{input('heroWord','الاسم الكبير في البطاقة')}{input('heroTagline','العبارة أسفل الاسم')}{input('heroButton','نص زر دخول المجالس')}</div>{area('homeDescription','وصف الصفحة الرئيسية')}{area('heroDescription','وصف بطاقة الترحيب')}<div className="home-setting-preview" style={{background:draft.primaryColor}}><small>{draft.heroLabel}</small><h3>{draft.heroHeading}</h3><p>{draft.heroDescription}</p><span>{draft.heroButton} ←</span></div></section></TabsContent>
  <TabsContent value="appearance"><section className="panel"><h2>ألوان الواجهة</h2><p>تطبق على الويب وواجهة الموبايل معًا بعد الحفظ.</p><div className="settings-grid">{([['primaryColor','اللون الرئيسي'],['accentColor','اللون المميز'],['backgroundColor','خلفية الموقع'],['textColor','لون النص']] as const).map(([key,label])=><label className="field" key={key}>{label}<div className="color-control"><input type="color" aria-label={label} value={draft[key]} onChange={e=>change(key,e.target.value)}/><input aria-label={'كود '+label} dir="ltr" value={draft[key]} pattern="#[a-fA-F0-9]{6}" onChange={e=>change(key,e.target.value)}/></div></label>)}</div><div className="theme-sample" style={{background:draft.backgroundColor,color:draft.textColor}}><b>{draft.siteName}</b><span style={{background:draft.accentColor}}>المجلس الرقمي</span><button type="button" style={{background:draft.primaryColor}}>معاينة زر</button></div></section></TabsContent>
  <TabsContent value="seo"><section className="panel"><h2>محركات البحث والمشاركة</h2><p>عنوان المتصفح، وصف الموقع، الرابط الأساسي وصورة المشاركة.</p><div className="settings-grid">{input('seoTitle','عنوان SEO / المتصفح','text','يفضل حوالي 50–60 حرفًا')}{input('canonicalUrl','الرابط الأساسي Canonical','url')}{input('seoKeywords','الكلمات المفتاحية','text','حقل وصفي؛ لا يضمن ترتيبًا في نتائج البحث')}{input('twitterHandle','اسم حساب X للمشاركة')}</div>{area('seoDescription','وصف SEO')}{image('seoImage','صورة المشاركة')}{toggle('robotsIndex','السماح بفهرسة الموقع','يُفضل إبقاؤه متوقفًا للبيانات التجريبية.')}<div className="seo-preview" aria-label="معاينة نتيجة البحث"><small>{draft.canonicalUrl||'رابط الموقع'}</small><h3>{draft.seoTitle}</h3><p>{draft.seoDescription}</p><span>{draft.seoTitle.length} حرف للعنوان · {draft.seoDescription.length} حرف للوصف</span></div><div className="notice"><Search size={18}/>{localMode?'معاينة SEO محلية. التعديلات لا تغيّر HTML المنشور للزوار أو لمحركات البحث؛ يلزم نشر الإعدادات من الخادم في النسخة الفعلية.':'هذه معاينة إعدادات. الفهرسة وصور المشاركة تحتاج توليد وسوم HTML على الخادم في النسخة الفعلية.'}</div></section></TabsContent>
  <TabsContent value="news"><section className="panel"><h2>إدارة الشريط الإخباري</h2><p>أضف الأخبار ورتبها وحدد الروابط وسلوك الحركة.</p>{toggle('tickerEnabled','إظهار الشريط الإخباري')}{toggle('tickerPause','إيقاف الحركة عند تمرير المؤشر')}<div className="settings-grid">{input('tickerTitle','عنوان الشريط')}{input('tickerSpeed','مدة الدورة بالثواني','number','رقم أكبر يعني حركة أبطأ — 15 إلى 180 ثانية')}<label className="field">اتجاه الحركة<select value={draft.tickerDirection} onChange={e=>change('tickerDirection',e.target.value)}><option value="left">إلى اليسار</option><option value="right">إلى اليمين</option></select></label></div><div className="news-items">{draft.tickerItems.map((n,i)=><div className="news-edit" key={n.id}><div className="news-item-heading"><b>خبر {i+1}</b><div className="row-actions"><button type="button" className="icon-btn" aria-label={'رفع ترتيب الخبر '+(i+1)} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={17}/></button><button type="button" className="icon-btn" aria-label={'خفض ترتيب الخبر '+(i+1)} disabled={i===draft.tickerItems.length-1} onClick={()=>move(i,1)}><ArrowDown size={17}/></button><button type="button" className="icon-btn danger-text" aria-label={'حذف الخبر '+(i+1)} onClick={()=>change('tickerItems',draft.tickerItems.filter(x=>x.id!==n.id))}><Trash2 size={17}/></button></div></div><label className="field">نص الخبر {i+1}<input value={n.text} onChange={e=>news(i,{text:e.target.value})} maxLength={500} required={n.enabled}/></label><label className="field">رابط الخبر {i+1} (اختياري)<input type="url" dir="ltr" value={n.url} onChange={e=>news(i,{url:e.target.value})}/></label><div className="switch-row"><b>تفعيل الخبر {i+1}</b><Switch dir="ltr" aria-label={'تفعيل الخبر '+(i+1)} checked={n.enabled} onCheckedChange={v=>news(i,{enabled:v})}/></div></div>)}</div><button className="btn outline" type="button" onClick={()=>change('tickerItems',[...draft.tickerItems,{id:'news-'+Date.now(),text:'',url:'',enabled:true}])}><Plus size={17}/>إضافة خبر</button></section></TabsContent>
  <TabsContent value="features"><section className="panel"><h2>خصائص المجالس والتواصل</h2><p>سياسة النشر والتعليقات لكل قسم تُدار من إدارة الأقسام. الصلاحيات الفردية من المنتسبين والمشرفين.</p>{toggle('chatEnabled','تفعيل الدردشة')}{toggle('streamsEnabled','تفعيل اللقاءات والبث')}{toggle('commentsEnabled','تفعيل التعليقات العامة')}{toggle('pinnedFirst','إظهار المواضيع المثبتة أولًا')}<div className="settings-grid">{input('postsPerPage','عدد المواضيع في الصفحة','number')}{input('postMaxLength','أقصى عدد حروف للموضوع','number')}{input('commentMaxLength','أقصى عدد حروف للتعليق','number')}{input('chatMaxLength','أقصى عدد حروف لرسالة الدردشة','number')}{input('currency','رمز العملة المعروض')}<label className="field">القسم الافتراضي للموضوع<select value={draft.defaultSection} onChange={e=>change('defaultSection',e.target.value)}>{sections.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select></label></div><div className="notice"><Check size={18}/>التسجيل برقم الجوال وموافقة الإدارة جزء من مسار العضوية. رمز OTP محاكاة في هذا العرض.</div></section></TabsContent>
  </Tabs><div className="settings-save"><span>{dirty?'لديك تعديلات لم تُحفظ':'الإعدادات محفوظة'}</span><button className="btn" type="submit" disabled={!dirty||saving}><Save size={17}/>{saving?'جارٍ الحفظ…':'حفظ الإعدادات'}</button>{dirty&&<button className="btn outline" type="button" onClick={()=>{setDraft(structuredClone(settings));changed.current.clear();setDirty(false);}}>إلغاء التعديلات</button>}</div></form>;
}
