export const names: Record<string,string> = {admin:'عبدالله الحقباني',mod:'ناصر الحقباني',m1:'محمد الحقباني',m2:'فهد الحقباني',m3:'خالد الحقباني',m4:'سعد الحقباني'};
export type DemoState = typeof initial;
export const initial = {
  sections:[{id:'news',title:'أخبار الديوان',description:'أخبارنا وإعلاناتنا الرسمية',icon:'megaphone',allowTopics:false,allowComments:true},{id:'majlis',title:'المجلس العام',description:'حديث يجمعنا ومساحة للجميع',icon:'coffee',allowTopics:true,allowComments:true},{id:'events',title:'المناسبات واللقاءات',description:'أفراح ولقاءات ومناسبات العائلة',icon:'calendar',allowTopics:true,allowComments:true},{id:'heritage',title:'ذاكرة الديوان',description:'حكايات وصور من إرثنا',icon:'book',allowTopics:true,allowComments:true}],
  members:[{id:'admin',name:'عبدالله الحقباني',phone:'+966 50 000 0001',status:'approved',role:'admin',restrictions:[] as string[],note:''},{id:'mod',name:'ناصر الحقباني',phone:'+966 50 000 0002',status:'approved',role:'mod',restrictions:[] as string[],note:''},{id:'m1',name:'محمد الحقباني',phone:'+966 50 000 0003',status:'approved',role:'member',restrictions:[] as string[],note:''},{id:'m2',name:'فهد الحقباني',phone:'+966 50 000 0004',status:'approved',role:'member',restrictions:[] as string[],note:''},{id:'m3',name:'خالد الحقباني',phone:'+966 50 000 0005',status:'pending',role:'member',restrictions:[] as string[],note:''},{id:'m4',name:'سعد الحقباني',phone:'+966 50 000 0006',status:'suspended',role:'member',restrictions:['topics','comments','chat'],note:'إيقاف مؤقت لحين مراجعة العضوية'}],
  posts:[{id:'p1',section:'news',sections:['news'],title:'لقاؤنا الشهري… نجتمع على المحبة',body:'يسعدنا دعوتكم إلى لقاء الديوان الشهري يوم الجمعة القادم، بعد صلاة العشاء. نلتقي بأبناء العائلة، ونناقش مبادرات الشهر المقبل.\n\nنرحب بأفكاركم واقتراحاتكم في التعليقات.',author:'admin',date:'2026-09-30T17:00:00',pinned:true,locked:false,hidden:false,comments:[{id:'c1',author:'m2',text:'بارك الله في جهودكم، بإذن الله نكون من الحاضرين.',date:'2026-09-30T17:20:00',hidden:false}]},{id:'p2',section:'majlis',sections:['majlis'],title:'ما المبادرات التي تحبون أن نبدأ بها؟',body:'نرغب بجمع أفكاركم لمبادرات الديوان القادمة. هل نبدأ بلقاء تعارف للشباب، أم برنامج لدعم الطلاب؟ شاركونا رأيكم.',author:'m1',date:'2026-09-29T18:00:00',pinned:false,locked:false,hidden:false,comments:[{id:'c2',author:'mod',text:'لقاء للشباب فكرة جميلة. خلونا نسمع باقي الآراء.',date:'2026-09-29T19:00:00',hidden:false}]},{id:'p3',section:'events',sections:['events'],title:'تهنئة لأبناء الديوان المتخرجين',body:'نتقدم بأطيب التهاني لأبنائنا وبناتنا المتخرجين، ونسأل الله لهم التوفيق في خطواتهم القادمة.',author:'mod',date:'2026-09-28T13:00:00',pinned:false,locked:false,hidden:false,comments:[]},{id:'p4',section:'heritage',sections:['heritage'],title:'من ذكريات مجالسنا الأولى',body:'هذه مساحة لحفظ روايات كبار العائلة وذكريات لقاءات الديوان. شاركونا ما تعرفونه من قصص موثوقة وأسماء أصحابها.',author:'m2',date:'2026-09-27T16:00:00',pinned:false,locked:false,hidden:false,comments:[]}],
  pages:[{id:'about',title:'عن الديوان',body:'يجمع ديوان الحقباني أبناء العائلة في مساحة للتواصل وصلة الرحم، وتبادل الأخبار وتنظيم اللقاءات.\n\nهذه بيانات توضيحية للعرض، ويُعتمد المحتوى الرسمي من إدارة الديوان.',published:true},{id:'rules',title:'ميثاق المشاركة',body:'نحافظ على الاحترام المتبادل، وخصوصية الأعضاء. تُنشر الأخبار من مصادرها، ويُمنع تداول بيانات شخصية دون إذن أصحابها.\n\nللمشرفين متابعة المشاركات بحسب الصلاحيات الممنوحة لهم.',published:true},{id:'contact',title:'إدارة الديوان',body:'للاستفسارات المتعلقة بالعضوية أو الاشتراكات، تواصل مع الإدارة عبر الدردشة الخاصة داخل الديوان.',published:true}],
  periods:[{id:'2026-09',label:'سبتمبر 2026',amount:100,due:'2026-09-05'},{id:'2026-10',label:'أكتوبر 2026',amount:100,due:'2026-10-05'}],
  payments:[{id:'r1',member:'m1',period:'2026-09',amount:100,status:'accepted',receipt:'',filename:'وصل_سبتمبر.pdf',reference:'TRX-0901',note:'تم التحقق من الحوالة',date:'2026-09-03',reviewer:'admin'},{id:'r2',member:'m2',period:'2026-09',amount:100,status:'pending',receipt:'',filename:'حوالة_فهد.jpg',reference:'TRX-0928',note:'',date:'2026-09-28',reviewer:''},{id:'r3',member:'mod',period:'2026-09',amount:100,status:'accepted',receipt:'',filename:'حوالة_ناصر.pdf',reference:'TRX-0902',note:'',date:'2026-09-02',reviewer:'admin'}],
  supervisors:[{member:'mod',sections:['majlis','events'],permissions:['moderate','pin','chat'],active:true}],
  messages:[{id:'msg1',thread:'general',author:'mod',text:'السلام عليكم، أهلًا بالجميع في مجلس الديوان.',date:'2026-09-30T15:00:00',hidden:false},{id:'msg2',thread:'general',author:'m2',text:'وعليكم السلام. شكرًا على هذه المساحة الجميلة.',date:'2026-09-30T15:02:00',hidden:false},{id:'msg3',thread:'admin:m1',author:'admin',text:'أهلًا محمد، يمكنك رفع وصل الاشتراك من صفحة اشتراكي.',date:'2026-09-30T16:00:00',hidden:false}],
  streams:[{id:'s1',title:'لقاء الديوان الشهري',description:'لقاء أبناء الديوان ومناقشة مبادرات الشهر القادم',platform:'YouTube',link:'https://www.youtube.com/live',date:'2026-10-02T20:00',status:'planned',launches:[] as {member:string,date:string}[],recording:'',confirmedBy:''},{id:'s2',title:'أمسية التعارف',description:'لقاء تعارف لأبناء العائلة',platform:'Zoom',link:'https://zoom.us/join',date:'2026-09-20T20:00',status:'confirmed',launches:[] as {member:string,date:string}[],recording:'',confirmedBy:'admin'}],
  settings:{
    siteName:'ديوان الحقباني',siteSubtitle:'المجلس الرقمي',
    homeTitle:'أهلًا بك في ديوان الحقباني',homeDescription:'هنا نجتمع، نتبادل الأخبار، ونبقى على تواصل.',
    heroLabel:'مجلسنا يجمعنا',heroHeading:'صلةٌ أقرب. ومجلسٌ يجمع الجميع.',heroDescription:'أخبار الديوان، حكايات العائلة، ولقاءاتنا القادمة.',heroWord:'الديوان',heroTagline:'أهلٌ ووصال',heroButton:'ادخل مجالس الديوان',
    footerText:'نموذج عرض ببيانات توضيحية. لا يمثل معلومات رسمية عن العائلة.',
    logo:'',favicon:'',primaryColor:'#194c3f',accentColor:'#d2b376',backgroundColor:'#f1f4f2',textColor:'#213c34',
    seoTitle:'ديوان الحقباني | المجلس الرقمي',seoDescription:'المجلس الرقمي لديوان الحقباني: أخبار الديوان، المجالس، اللقاءات والتواصل بين المنتسبين. نموذج تفاعلي تجريبي.',seoKeywords:'ديوان الحقباني، مجالس، أخبار الديوان',seoImage:'',canonicalUrl:'https://salahassi.github.io/Deewan/',robotsIndex:false,twitterHandle:'',
    contactEmail:'',contactPhone:'',contactAddress:'',instagramUrl:'',youtubeUrl:'',xUrl:'',
    tickerEnabled:true,tickerTitle:'أخبار الديوان',tickerSpeed:45,tickerDirection:'left',tickerPause:true,
    tickerItems:[{id:'news1',text:'أهلًا بكم في المجلس الرقمي لديوان الحقباني',url:'',enabled:true},{id:'news2',text:'لقاء الديوان الشهري يوم الجمعة القادم — نلتقي على المحبة',url:'',enabled:true}],
    chatEnabled:true,streamsEnabled:true,commentsEnabled:true,postMaxLength:20000,commentMaxLength:2000,chatMaxLength:2000,postsPerPage:10,pinnedFirst:true,defaultSection:'majlis',currency:'ر.س',
    amount:100,dueDay:5,bank:'حساب الديوان — بيانات توضيحية',iban:'SA00 0000 0000 0000 0000 0000',autoRules:[] as string[]},
  log:[{id:'l1',actor:'admin',text:'اعتماد حوالة محمد لشهر سبتمبر',date:'2026-09-03T13:00:00'}]
};
